name: notesprout_mobile

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  notesprout_core:
    path: ../../packages/notesprout_core
  path_provider: ^2.1.5
  intl: ^0.20.2
