package com.notesprout.android.notebook

import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.widget.LinearLayout

/**
 * Manages toolbar overflow for NotebookActivity.
 *
 * When all buttons + dividers fit within the toolbar, the toolbar renders exactly as
 * defined in XML with btnOverflow/dividerOverflow hidden.  When they don't fit, the
 * trailing items that exceed the available extent are moved into an overflow menu that
 * opens away from the bar (below a top bar, beside a side bar, …).
 *
 * Axis-aware: it reads the bar's current [LinearLayout.orientation] every pass, so it works
 * for horizontal (TOP/BOTTOM) and vertical (LEFT/RIGHT) placements alike. "Width" becomes the
 * bar's main-axis extent and overflow rows become columns for a vertical bar. [ToolbarLayoutManager]
 * sets the orientation; the Activity sizes/positions [overflowMenu] to match.
 *
 * Views are MOVED (not cloned), so isSelected state, icon state, and click listeners
 * are all preserved automatically across toolbar ↔ overflow transitions.
 *
 * Call [initialize] from the toolbar's first doOnLayout, then [recalc] whenever the
 * toolbar extent changes (e.g. rotation, placement change).
 */
class ToolbarOverflowManager(
    private val toolbar: LinearLayout,
    private val overflowMenu: LinearLayout,
    private val dividerOverflow: View,
    private val btnOverflow: View,
) {
    /** True when the bar is laid out vertically (LEFT/RIGHT placement). Read fresh each pass. */
    private val isVertical get() = toolbar.orientation == LinearLayout.VERTICAL
    /** All moveable toolbar items (buttons + group dividers) in original left-to-right order.
     *  Does NOT include the flexible Space, dividerOverflow, or btnOverflow. */
    private var originalOrder: List<View> = emptyList()

    /** The weight=1 Space view (generated by ToolbarLayoutManager) that pins the overflow controls
     *  to the trailing edge. Always kept in the toolbar; never moved to the overflow menu. */
    private var spaceView: View? = null

    private var initialized = false

    // ── Public API ────────────────────────────────────────────────────────────

    fun initialize() {
        if (initialized) return
        val moveable = mutableListOf<View>()
        var space: View? = null
        for (i in 0 until toolbar.childCount) {
            val child = toolbar.getChildAt(i)
            if (child === dividerOverflow || child === btnOverflow) continue
            val lp = child.layoutParams as? LinearLayout.LayoutParams
            if ((lp?.weight ?: 0f) > 0f) {
                space = child
            } else {
                moveable.add(child)
            }
        }
        originalOrder = moveable
        spaceView = space
        initialized = true
    }

    /**
     * Recalculates which buttons stay in the toolbar and which overflow.
     * Safe to call on every toolbar-width change; closes the overflow menu first.
     */
    fun recalc() {
        if (!initialized) initialize()
        val available = mainAxisExtent()
        if (available <= 0) return

        val overflowReserve = naturalSize(dividerOverflow) + naturalSize(btnOverflow)
        val capacity = available - overflowReserve
        val naturalTotal = originalOrder.sumOf { naturalSize(it) }

        if (naturalTotal <= available) {
            rebuildAll(inToolbar = originalOrder, inOverflow = emptyList(), showOverflow = false)
            return
        }

        // Find the largest prefix of originalOrder that fits within capacity.
        var cumulative = 0
        var cutIndex = originalOrder.size
        for (i in originalOrder.indices) {
            val w = naturalSize(originalOrder[i])
            if (cumulative + w > capacity) {
                cutIndex = i
                break
            }
            cumulative += w
        }

        // Don't leave a group divider as the last visible item in the toolbar —
        // it would sit immediately before dividerOverflow, doubling the visual separator.
        if (cutIndex > 0 && isDivider(originalOrder[cutIndex - 1])) {
            cutIndex--
        }

        rebuildAll(
            inToolbar  = originalOrder.subList(0, cutIndex),
            inOverflow = originalOrder.subList(cutIndex, originalOrder.size),
            showOverflow = true,
        )
    }

    /**
     * Forces the next [recalc] to re-derive [originalOrder] / [spaceView] from the toolbar's current
     * children. Call after [ToolbarLayoutManager.apply] rebuilds the bar (reorder / show-hide), since
     * the moveable set and the auto-generated dividers have changed.
     */
    fun reset() { initialized = false }

    fun openOverflowMenu()  { overflowMenu.visibility = View.VISIBLE }
    fun closeOverflowMenu() { overflowMenu.visibility = View.GONE }
    fun isOverflowMenuOpen() = overflowMenu.visibility == View.VISIBLE

    /**
     * Returns the expected pixel extent of the overflow menu *away from the bar* — the number of
     * packed lines (rows for a horizontal bar, columns for a vertical bar) times the bar's
     * cross-axis thickness — computed synchronously without a layout pass.  Use this to extend the
     * BOOX exclusion zone immediately when the menu opens, before wrap_content measurement runs.
     */
    fun expectedOverflowMenuExtent(): Int = overflowMenu.childCount * barThickness()

    // ── Private helpers ───────────────────────────────────────────────────────

    private fun rebuildAll(inToolbar: List<View>, inOverflow: List<View>, showOverflow: Boolean) {
        // Detach all moveable views from wherever they currently live (toolbar or overflow rows).
        for (child in originalOrder) (child.parent as? ViewGroup)?.removeView(child)
        spaceView?.let { (it.parent as? ViewGroup)?.removeView(it) }

        // Clear whatever remains in the toolbar (dividerOverflow + btnOverflow).
        toolbar.removeAllViews()
        // Clear overflow row containers.
        overflowMenu.removeAllViews()

        // Rebuild toolbar: [in-toolbar items] [Space] [dividerOverflow] [btnOverflow]
        for (child in inToolbar) toolbar.addView(child)
        spaceView?.let { toolbar.addView(it) }
        toolbar.addView(dividerOverflow)
        toolbar.addView(btnOverflow)

        dividerOverflow.visibility = if (showOverflow) View.VISIBLE else View.GONE
        btnOverflow.visibility     = if (showOverflow) View.VISIBLE else View.GONE
        overflowMenu.visibility    = View.GONE // always collapsed after a recalc

        if (showOverflow) buildOverflowRows(inOverflow)
    }

    /**
     * Packs [items] into one or more lines inside [overflowMenu], greedy along the bar's main axis:
     * rows (left-to-right) for a horizontal bar, columns (top-to-bottom) for a vertical bar.  Group
     * dividers between items are preserved exactly as in the toolbar.
     */
    private fun buildOverflowRows(items: List<View>) {
        if (items.isEmpty()) return
        val lineCapacity = mainAxisExtent()
        var line = newLine()
        overflowMenu.addView(line)
        var lineUsed = 0
        for (item in items) {
            val w = naturalSize(item)
            if (lineUsed > 0 && lineUsed + w > lineCapacity) {
                line = newLine()
                overflowMenu.addView(line)
                lineUsed = 0
            }
            line.addView(item)
            lineUsed += w
        }
    }

    /** A single packing line in the overflow menu: a horizontal row (bar thickness tall, full width)
     *  for a horizontal bar, or a vertical column (bar thickness wide, full height) for a vertical bar. */
    private fun newLine() = LinearLayout(toolbar.context).apply {
        if (isVertical) {
            orientation = LinearLayout.VERTICAL
            gravity = Gravity.CENTER_HORIZONTAL
            layoutParams = LinearLayout.LayoutParams(
                barThickness(),
                ViewGroup.LayoutParams.MATCH_PARENT,
            )
        } else {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            layoutParams = LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                barThickness(),
            )
        }
    }

    /** The toolbar's main-axis extent (the dimension items pack along) minus padding. */
    private fun mainAxisExtent(): Int = if (isVertical) {
        toolbar.height - toolbar.paddingTop - toolbar.paddingBottom
    } else {
        toolbar.width - toolbar.paddingStart - toolbar.paddingEnd
    }

    /** The bar's cross-axis thickness in px (its width when vertical, its height when horizontal). */
    private fun barThickness(): Int = if (isVertical) toolbar.width else toolbar.height

    /**
     * Returns the space a view occupies along the bar's main axis in a LinearLayout: its LayoutParams
     * main-axis dimension (in px) plus the two margins on that axis. Works correctly for GONE views
     * whose measured size is 0.
     */
    private fun naturalSize(view: View): Int {
        val lp = view.layoutParams as? ViewGroup.MarginLayoutParams ?: return 0
        return if (isVertical) {
            val h = if (lp.height >= 0) lp.height else 0 // exact px; skip WRAP/MATCH
            h + lp.topMargin + lp.bottomMargin
        } else {
            val w = if (lp.width >= 0) lp.width else 0
            w + lp.leftMargin + lp.rightMargin
        }
    }

    /** True for plain View dividers (1dp black lines), false for buttons and Space. */
    private fun isDivider(view: View): Boolean = view.javaClass == View::class.java
}
